package com.projeto.exception;

import org.springframework.http.HttpStatus;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum TabelaDeErros {
	
	VALIDACAO (HttpStatus.BAD_REQUEST ,"1000 - 1000", "DADOS DE REQUISIÇÃO INVÁLIDOS, TENTE NOVAMENTE"),
	
	PEDIDO_NAO_ENCONTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, PEDIDO NÃO ENCONTRADO"),
	CLIENTE_NAO_ENCONTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, CLIENTE NÃO ENCONTRADO"),
	PRODUTO_NAO_ENCONTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, PRODUTO NÃO ENCONTRADO"),
	ENDERECO_NAO_CADASTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, ENDEREÇO NÃO ENCONTRADO"),
	TELEFONE_NAO_CADASTRADO (HttpStatus.NOT_FOUND,"1000 - 3001", "INFORMAÇÕES INVÁLIDAS, TELEFONE NÃO ENCONTRADO"),

	
	CPF_JA_CADASTRADO (HttpStatus.CONFLICT ,"1000 - 4009", "O CPF JÁ CONSTA NA BASE DE DADOS"),
	ENDERECO_JA_CADASTRADO (HttpStatus.CONFLICT ,"1000 - 4009", "O ENDEREÇO JÁ CONSTA NA BASE DE DADOS"),
	PRODUTO_JA_CADASTRADO (HttpStatus.CONFLICT ,"1000 - 4009", "ESSE PRODUTO JÁ CONSTA NA BASE DE DADOS"),
	TELEFONE_JA_CADASTRADO (HttpStatus.CONFLICT ,"1000 - 4009", "ESSE NÚMERO JÁ CONSTA NA BASE DE DADOS"),
	
	SISTEMA(HttpStatus.INTERNAL_SERVER_ERROR,"1000 - 5000", "SISTEMA INDISPONÍVEL, TENTE MAIS TARDE");

	private final HttpStatus codigoHttp;
	private final String codigoErro;
	private final String mensagem;
	

}
